### ISSUE TITLE
Why no multithreading support?

### ISSUE THREAD

**Issue by Rapix-x** [zeebo/blake3#7] opened 2020-04-11 20:32 UTC
Hi zeebo, you outline in the README that multithreading is not support. I'm just wondering why you made that choice. Can you give some background on that?

**Comment by zeebo** [comment] 2020-04-14 18:03
I tried to write up something about this in the readme but was never satisfied that I could make the arguments clearly. I'll try here, but let me know if you have any more questions.

I'll start with some underlying constraints:
1. In Go, an io.Writer has the contract that it should not hold references to the passed in buffer after the function call has returned.
2. It does not make sense to have concurrent writers to the hasher: since by definition their ordering isn't known, the output of the hash cannot be known either.
3. In order to benefit from multi-threading, you have to have a large enough data set to work on. This library makes the decision to try to operate on SIMD maximally sized buffers (8k), so for N threads we would need to buffer N*8k data.

That means that the hasher will always be used in a single threaded context, and that we have to handle all of the data in some way before the Write call returns. That, in turn, means that callers must provide a large enough (at least 16K for 2 threads) buffer to each Write call, or we must have a large enough internal buffer.

Making the internal buffer larger has a cost besides just using more memory: small hashes are more expensive because it takes longer to initialize the hash state due to Go's requirement of zeroing allocated memory. 8K is already pushing the boundary of what I would consider to be reasonable. The optimal internal buffer size also depends on how many threads you want to use. There's no obviously correct answer there, so you can either increase the API surface to allow users to specify or attempt to make a guess based on the system. In either case, your buffer now is a dynamic size, which reduces compiler optimizations and adds an indirection to read/write it.

Given the challenges with sizing the internal buffer appropriately, the only other option is if the Write call is large enough to do multiple hashes in parallel. My guess is that situation is fairly rare: I expect most hash inputs don't even meet the 8k size requirement. And even then, since the single threaded rate is at ~4GB/sec, your input source must go faster than that in order to benefit from multithreading. That discounts pretty much everything coming from the network, and plenty of situations from disk. For example, I only get ~2GB/sec reads from my nvme ssd drive if they aren't cached.

On a less technical challenge level, I prefer when libraries don't decide to use all of my CPU cores just because they're "available". It's hard to make that determination without a holistic view of the system, and so using excess CPU in the hash step may make things worse. For example, consider if I had a bunch of input streams that I wanted to hash in parallel. Adding multithreading to each individual hash could be a performance regression.

So it was just a cost/benefit decision. There are substantial difficult questions to answer with their own tradeoffs and I don't see enough benefit to make it worth it.

---

I'm going to close this issue under the optimistic assumption that my answer was sufficient. Thanks!

**Closed by zeebo** 2020-04-14 18:03 UTC
